namespace adovipavto.Enums
{
    internal enum Normatives
    {
        OUTCRTS,
        OUTCSTS,
        ORTS1,
        ORTS2,
        ORTS3,
        MVSTS,
        KUNOU,
        SL,
        SSFBS,
        SSFDS,
        SSPF,
        CHPUP,
        OVRP,
        SCOMCHV,
        SCOPCHV,
        SCHMCHV,
        SCHPCHV,
        DVRSUM,
        DVRSUP,
        CHVNMO,
        CHVNPO,
        PVS,
        PPBS,
        VSHA
    }
}