using System;
using System.IO;
using System.Text;
using System.Xml;
using System.Xml.Serialization;

namespace adovipavto.Classes
{
    [XmlRoot(elementName: "Settings")]
    public class Settings
    {
        private static Settings _instance;

        public static Settings Instance
        {
            get
            {
                if (_instance == null)
                {
                    _instance = new Settings();
                }
                return _instance;
            }
        }

        [XmlElement("Protocols")]
        public string Protocols { get; set; }
        [XmlElement("Groups")]
        public string Groups { get; set; }
        [XmlElement("Normatives")]
        public string Normatives { get; set; }
        [XmlElement("Operators")]
        public string Operators { get; set; }
        [XmlElement("Mechanics")]
        public string Mechanics { get; set; }
        [XmlElement("Language")]
        public string Language { get; set; }
        [XmlElement("Mesure")]
        public string Mesure { get; set; }
        [XmlElement("AutoGeneratedData")]
        public bool AutoGeneratedData { get; set; }
        [XmlElement("BackupDirectory")]
        public string BackupDirectory { get; set; }
        [XmlElement("FilesDirectory")]
        public string FilesDirectory { get; set; }
        [XmlElement("LastUsedMechanic")]
        public string LastUsedMechanic { get; set; }
        [XmlElement("TmpLanguage")]
        public string TmpLanguage { get; set; }

        readonly string _fileSettingPath = "settings.xml";

        private Settings()
        {

            string path = Path.GetPathRoot(Environment.SystemDirectory) + @"DiagnostikaData\";

            if (!Directory.Exists(path))
            {
                Directory.CreateDirectory(path);

            }

            FilesDirectory = path;

            if (!File.Exists(FilesDirectory + _fileSettingPath))
            {
                var myFile = File.Create(FilesDirectory + _fileSettingPath);
                myFile.Close();

                Protocols = "protocols.xml";
                Groups = "groups.xml";
                Normatives = "normatives.xml";
                Operators = "operators.xml";
                Mechanics = "mechanics.xml";
                Language = "";
                Mesure = "mesure.xml";
                AutoGeneratedData = false;
                BackupDirectory = "";
                LastUsedMechanic = "";
                TmpLanguage = "";

            }
        }

        public void Load()
        {
                var serializer = new XmlSerializer(this.GetType());
            using (var reader = new StreamReader(FilesDirectory + _fileSettingPath))
            {
                var tmp = (Settings) serializer.Deserialize(reader);

                AutoGeneratedData = tmp.AutoGeneratedData;
                BackupDirectory = tmp.BackupDirectory;
                FilesDirectory = tmp.FilesDirectory;
                Groups = tmp.Groups;
                Language = tmp.Language;
                LastUsedMechanic = tmp.LastUsedMechanic;
                Mechanics = tmp.Mechanics;
                Mesure = tmp.Mesure;
                Normatives = tmp.Normatives;
                Operators = tmp.Operators;
                Protocols = tmp.Protocols;
                TmpLanguage = tmp.TmpLanguage;
            }

        }


        public void Save()
        {
            var serializer = new XmlSerializer(typeof(Settings));

            XmlWriter xw = new XmlTextWriter(FilesDirectory + _fileSettingPath, Encoding.UTF8);
            serializer.Serialize(xw, _instance);
            xw.Close();


        }


    }
}
