//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace adovipavto.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("adovipavto.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap about {
            get {
                object obj = ResourceManager.GetObject("about", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Buttons_0005_Mech {
            get {
                object obj = ResourceManager.GetObject("Buttons_0005_Mech", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Buttons_0005_PLUSMech {
            get {
                object obj = ResourceManager.GetObject("Buttons_0005_PLUSMech", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Buttons_0005_PLUSMech1 {
            get {
                object obj = ResourceManager.GetObject("Buttons_0005_PLUSMech1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Buttons_0006_FIREMech {
            get {
                object obj = ResourceManager.GetObject("Buttons_0006_FIREMech", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Buttons_0006_FIREMech1 {
            get {
                object obj = ResourceManager.GetObject("Buttons_0006_FIREMech1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Buttons_0007_EDIT {
            get {
                object obj = ResourceManager.GetObject("Buttons_0007_EDIT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Buttons_0007_EDIT_copy {
            get {
                object obj = ResourceManager.GetObject("Buttons_0007_EDIT_copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Buttons_0008_ADDOper {
            get {
                object obj = ResourceManager.GetObject("Buttons_0008_ADDOper", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Buttons_0009_FIREOper {
            get {
                object obj = ResourceManager.GetObject("Buttons_0009_FIREOper", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Buttons_0009_Oper {
            get {
                object obj = ResourceManager.GetObject("Buttons_0009_Oper", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Buttons_0010_EDITOper {
            get {
                object obj = ResourceManager.GetObject("Buttons_0010_EDITOper", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cancel {
            get {
                object obj = ResourceManager.GetObject("cancel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Частота проблесков указателей поворота (Гц).
        /// </summary>
        internal static string CHPUP {
            get {
                return ResourceManager.GetString("CHPUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Частота вращения на минимальных оборотах (об. мин).
        /// </summary>
        internal static string CHVNMO {
            get {
                return ResourceManager.GetString("CHVNMO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Частота вращения на повышеных оборотах (об. мин).
        /// </summary>
        internal static string CHVNPO {
            get {
                return ResourceManager.GetString("CHVNPO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap copy {
            get {
                object obj = ResourceManager.GetObject("copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дымность в режиме свободных ускорений (м-1).
        /// </summary>
        internal static string DVRSUM {
            get {
                return ResourceManager.GetString("DVRSUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дымность в режиме свободных ускорений (%).
        /// </summary>
        internal static string DVRSUP {
            get {
                return ResourceManager.GetString("DVRSUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap edit {
            get {
                object obj = ResourceManager.GetObject("edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap exit {
            get {
                object obj = ResourceManager.GetObject("exit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fail {
            get {
                object obj = ResourceManager.GetObject("fail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap green {
            get {
                object obj = ResourceManager.GetObject("green", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GROUP {
            get {
                object obj = ResourceManager.GetObject("GROUP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap help {
            get {
                object obj = ResourceManager.GetObject("help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap help1 {
            get {
                object obj = ResourceManager.GetObject("help1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контрольное усилие на орган управления (1-я ось)(Н).
        /// </summary>
        internal static string KUNOU1 {
            get {
                return ResourceManager.GetString("KUNOU1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Общая удельная тормозная сила рабочей ТС (доли ед.)
        ///Общая удельная тормозная сила стояночной ТС (доли ед.)
        ///Отн. разность тормозных сил (1-я ось)(доли ед.)
        ///Отн. разность тормозных сил (2-я ось)(доли ед.)
        ///Отн. разность тормозных сил (3-я ось)(доли ед.)
        ///Максимальное время срабатывания ТС (мс)
        ///Контрольное усилие на орган управления (1-я ось)(Н)
        ///Суммарный люфт (град)
        ///Сила света фар ближнего света (Кд)
        ///Сила света фар дальнего света (Кд)
        ///Сила света противотуманных фар (Кд)
        ///Частота проблесков указателей  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mesures {
            get {
                return ResourceManager.GetString("mesures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap minus {
            get {
                object obj = ResourceManager.GetObject("minus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Максимальное время срабатывания ТС (мс).
        /// </summary>
        internal static string MVSTS {
            get {
                return ResourceManager.GetString("MVSTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap none {
            get {
                object obj = ResourceManager.GetObject("none", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NORMARIVES {
            get {
                object obj = ResourceManager.GetObject("NORMARIVES", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap openfoto {
            get {
                object obj = ResourceManager.GetObject("openfoto", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отн. разность тормозных сил (1-я ось)(доли ед.).
        /// </summary>
        internal static string ORTS1 {
            get {
                return ResourceManager.GetString("ORTS1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отн. разность тормозных сил (2-я ось)(доли ед.).
        /// </summary>
        internal static string ORTS2 {
            get {
                return ResourceManager.GetString("ORTS2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отн. разность тормозных сил (3-я ось)(доли ед.).
        /// </summary>
        internal static string ORTS3 {
            get {
                return ResourceManager.GetString("ORTS3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Общая удельная тормозная сила рабочей ТС (доли ед.).
        /// </summary>
        internal static string OUTSRTS {
            get {
                return ResourceManager.GetString("OUTSRTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Общая удельная тормозная сила стояночной ТС (доли ед.).
        /// </summary>
        internal static string OUTSSTS {
            get {
                return ResourceManager.GetString("OUTSSTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Остаточная высота рисунка протектора (мм).
        /// </summary>
        internal static string OVRP {
            get {
                return ResourceManager.GetString("OVRP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pass {
            get {
                object obj = ResourceManager.GetObject("pass", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap plus {
            get {
                object obj = ResourceManager.GetObject("plus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прозрачность переднего бокового стекла (%).
        /// </summary>
        internal static string PPBS {
            get {
                return ResourceManager.GetString("PPBS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap preview {
            get {
                object obj = ResourceManager.GetObject("preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap print {
            get {
                object obj = ResourceManager.GetObject("print", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap print1 {
            get {
                object obj = ResourceManager.GetObject("print1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap printsetting {
            get {
                object obj = ResourceManager.GetObject("printsetting", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap protocol1 {
            get {
                object obj = ResourceManager.GetObject("protocol1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прозрачность ветрового стекла (%).
        /// </summary>
        internal static string PVS {
            get {
                return ResourceManager.GetString("PVS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap red {
            get {
                object obj = ResourceManager.GetObject("red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap russia_icon {
            get {
                object obj = ResourceManager.GetObject("russia_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap save {
            get {
                object obj = ResourceManager.GetObject("save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Содержание СН: повышенная частота вращения(ppm).
        /// </summary>
        internal static string SCHMACHV {
            get {
                return ResourceManager.GetString("SCHMACHV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Содержание СН: минимальная частота вращения (ppm).
        /// </summary>
        internal static string SCHMCHV {
            get {
                return ResourceManager.GetString("SCHMCHV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Содержание СО: повышенная частота вращения(%).
        /// </summary>
        internal static string SCOMACHV {
            get {
                return ResourceManager.GetString("SCOMACHV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Содержание СО: минимальная частота вращения (%).
        /// </summary>
        internal static string SCOMCHV {
            get {
                return ResourceManager.GetString("SCOMCHV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap search {
            get {
                object obj = ResourceManager.GetObject("search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap setting {
            get {
                object obj = ResourceManager.GetObject("setting", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sign_logoff {
            get {
                object obj = ResourceManager.GetObject("sign_logoff", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Суммарный люфт (град).
        /// </summary>
        internal static string SL {
            get {
                return ResourceManager.GetString("SL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap splashScreen {
            get {
                object obj = ResourceManager.GetObject("splashScreen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap splashScreen2 {
            get {
                object obj = ResourceManager.GetObject("splashScreen2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сила света фар ближнего света (Кд).
        /// </summary>
        internal static string SSFBS {
            get {
                return ResourceManager.GetString("SSFBS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сила света фар дальнего света (Кд).
        /// </summary>
        internal static string SSFDS {
            get {
                return ResourceManager.GetString("SSFDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сила света противотуманных фар (Кд).
        /// </summary>
        internal static string SSPF {
            get {
                return ResourceManager.GetString("SSPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ukraine_icon {
            get {
                object obj = ResourceManager.GetObject("ukraine_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Внешний шум автомобиля (дБА).
        /// </summary>
        internal static string VSHA {
            get {
                return ResourceManager.GetString("VSHA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Внимание.
        /// </summary>
        internal static string warning {
            get {
                return ResourceManager.GetString("warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap yellow {
            get {
                object obj = ResourceManager.GetObject("yellow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
