using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace adovipavto
{
    public partial class SettingForm : Form
    {
        public SettingForm()
        {
            Thread.CurrentThread.CurrentUICulture = new CultureInfo(Properties.Settings.Default.Language);

            InitializeComponent();
        }

        private void button2_Click(object sender, EventArgs e)
        {
            DialogResult = DialogResult.Cancel;
        }

        private void button1_Click(object sender, EventArgs e)
        {

                if (radioButton1.Checked)
                    Properties.Settings.Default.Language = "ru-RU";
                else
                    Properties.Settings.Default.Language = "uk-UA";

                Properties.Settings.Default.AutoGeneratedData = radioButton3.Checked;


                string oldPath = Properties.Settings.Default.FilesDirectory;
                if (oldPath != textBox1.Text)
                {
                    if (oldPath == "")
                        oldPath = Directory.GetCurrentDirectory();

                    foreach (string file in Directory.GetFiles(oldPath))
                    {
                        if (file.Split(new char[] { '.' }, StringSplitOptions.RemoveEmptyEntries).Last() == "xml")
                        {
                            string newFile = textBox1.Text +
                                             file.Split(new char[] { '\\' }, StringSplitOptions.RemoveEmptyEntries).Last();
                            if (!File.Exists(newFile))
                                File.Move(file, newFile);
                        }
                    }
                }




                Properties.Settings.Default.FilesDirectory = textBox1.Text;

                Properties.Settings.Default.BackupDirectory = textBox2.Text;

                Properties.Settings.Default.Save();

                DialogResult = DialogResult.OK;
        }

        private void button3_Click(object sender, EventArgs e)
        {
            if (folderBrowserDialog1.ShowDialog() == DialogResult.OK)
            {
                if (folderBrowserDialog1.SelectedPath.Last() == '\\')
                    textBox1.Text = folderBrowserDialog1.SelectedPath;
                else
                {
                    textBox1.Text = folderBrowserDialog1.SelectedPath + "\\";
                }
            }
        }

        private void button4_Click(object sender, EventArgs e)
        {
            if (folderBrowserDialog1.ShowDialog() == DialogResult.OK)
                textBox2.Text = folderBrowserDialog1.SelectedPath;
        }

        private void SettingForm_Load(object sender, EventArgs e)
        {
            if (Properties.Settings.Default.Language == "ru-RU")
                radioButton1.Checked = true;
            else
            {
                radioButton2.Checked = true;
            }

            if (Properties.Settings.Default.AutoGeneratedData)
                radioButton3.Checked = true;
            else
                radioButton4.Checked = true;

            textBox1.Text = Properties.Settings.Default.FilesDirectory;

            textBox2.Text = Properties.Settings.Default.BackupDirectory;

        }
    }
}
